
import Memoria.Memoria;
import Note.ListaNote;
import Note.NotaConAllert;
import Note.Nota;
import javax.swing.JOptionPane;


public class PaginaReminders extends javax.swing.JFrame {

    Memoria memoria;
    MainPage contestoPrincipale;
    ListaNote listaNote;

    public void updateComponenteListaRemindersModel() {
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = estraiArrayDiNomiDaNoteConAllert();

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    //prende solo i nomi delle note che hanno allert true
    public String[] estraiArrayDiNomiDaNoteConAllert() {
        int count = 0;
        for (int i = 0; i < listaNote.listaNote.size(); i++) {
            Nota nota = listaNote.listaNote.get(i);
            if (nota instanceof NotaConAllert) {
                if (((NotaConAllert) nota).isAllertAttivo()) {
                    count++;
                }
            }
        }

        String[] strings = new String[count];
        int index = 0;
        for (int i = 0; i < listaNote.listaNote.size(); i++) {
            Nota nota = listaNote.listaNote.get(i);
            if (nota instanceof NotaConAllert) {
                if (((NotaConAllert) nota).isAllertAttivo()) {
                    strings[index] = nota.titolo;
                    index++;
                }
            }
        }
        return strings;
    }

  
    public PaginaReminders() {
        initComponents();
    }
    // prende gli argomenti necssari tra cui il context esterno per aggiornare il model
    public PaginaReminders(Memoria memoriaEsterna, MainPage contestoPrincipale, ListaNote listaNoteEsterna) {
        this.memoria = memoriaEsterna;
        this.contestoPrincipale = contestoPrincipale;
        this.listaNote = listaNoteEsterna;
        initComponents();
        if (contestoPrincipale != null) {
            contestoPrincipale.setEnabled(false);
        }
        getContentPane().setBackground(new java.awt.Color(255, 204, 204));
        updateComponenteListaRemindersModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bottoneDisattivaAllert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setBackground(new java.awt.Color(255, 230, 230));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        bottoneDisattivaAllert.setText("Disattiva tutti gli Allert e chiudi");
        bottoneDisattivaAllert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneDisattivaAllertActionPerformed(evt);
            }
        });

        jLabel1.setText("!! ATTENZIONE !!");

        jLabel2.setText("QUESTE NOTE SONO PARTICOLARMENTE IMPORTANTI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(bottoneDisattivaAllert)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottoneDisattivaAllert)
                                .addContainerGap(60, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // gestisce il click sui valori della lista par aprire notaAperta
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
        Object valoreSelezionato = jList1.getSelectedValue();

        if (valoreSelezionato != null) {
            final int posizioneOggettoCorrente = listaNote.returnJsonPositionInList(valoreSelezionato.toString());

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    PaginaNotaAperta pna = new PaginaNotaAperta(memoria, contestoPrincipale, listaNote,
                            posizioneOggettoCorrente,
                            PaginaReminders.this);
                    pna.setLocationRelativeTo(PaginaReminders.this);
                    java.awt.Point p = pna.getLocation();
                    pna.setLocation(p.x + 30, p.y + 30);
                    pna.setVisible(true);
                }
            });
        } else {
            JOptionPane.showMessageDialog(this, "Devi prima selezionare un elemento dalla lista.");
        }
    }// GEN-LAST:event_jList1MouseClicked

    // il bottone che dissattiva tutti gli allert attivi e chiude la pagina
    private void bottoneDisattivaAllertActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bottoneDisattivaAllertActionPerformed
        for (int i = 0; i < listaNote.listaNote.size(); i++) {
            Nota nota = listaNote.listaNote.get(i);
            if (nota instanceof NotaConAllert) {
                NotaConAllert notaConAllert = (NotaConAllert) nota;
                if (notaConAllert.isAllertAttivo()) {
                    notaConAllert.setAllertAttivo(false);
                    try {
                        memoria.rimuoviDaCSV(nota);
                        memoria.salvaEControllaDuplicatiInCSV(nota);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }
        contestoPrincipale.updateComponenteListaNoteModel();
        this.dispose();
    }

    // si occupa di disattivare la pagina padre che può essere solo la principale
    @Override
    public void dispose() {
        if (contestoPrincipale != null) {
            contestoPrincipale.setEnabled(true);
            contestoPrincipale.toFront();
        }
        super.dispose();
    }
    
    
    
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaReminders.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaReminders.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaReminders.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaReminders.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
       

      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaReminders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneDisattivaAllert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
